name: Annotation Image Test

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  image-annotation:
    runs-on: ubuntu-latest
    steps:
      - name: Add markdown image job summary
        run: |
          echo "## Markdown image test" >> "$GITHUB_STEP_SUMMARY"
          echo "![This is fine](https://en.wikipedia.org/wiki/File:This_is_fine_from_On_Fire_strip_by_KC_Green.jpg#/media/File:This_is_fine_from_On_Fire_strip_by_KC_Green.jpg)" >> "$GITHUB_STEP_SUMMARY"
